# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

2.3.3
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.3
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/build-env

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
Z = np.zeros((10,10))
print(f"Memory size of array: {Z.size * Z.itemsize} bytes")

Memory size of array: 800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# python3 -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
X = np.arange(10,50)
X

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
X = X[::-1]
X

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
X = np.arange(0,9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
X = [1,2,0,0,4,0]
ind = np.nonzero(X)
ind

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
X = np.eye(3)
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
X = np.random.random((3,3,3))
X

array([[[0.97985212, 0.71931918, 0.35196328],
        [0.53635962, 0.10779727, 0.29233496],
        [0.86650335, 0.30418305, 0.96416977]],

       [[0.23358752, 0.78736195, 0.63576516],
        [0.83416973, 0.67909262, 0.95654365],
        [0.81246516, 0.25787881, 0.51288998]],

       [[0.47837441, 0.80592829, 0.98831248],
        [0.86114373, 0.79687542, 0.72450643],
        [0.50804476, 0.30776614, 0.16066727]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
X = np.random.random((10,10))
Xmax, Xmin = X.max(), X.min()

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
X = np.random.random(30)
np.mean(X)

np.float64(0.5103062142159659)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
X = np.ones((10,10))
X[1:-1, 1:-1] = 0
X

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
X = np.random.random((5,5)).round(2)
X = np.pad(X, pad_width=1, mode='constant', constant_values=0)
X

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.95, 0.84, 0.31, 0.15, 0.6 , 0.  ],
       [0.  , 0.53, 0.56, 0.7 , 0.51, 0.53, 0.  ],
       [0.  , 0.94, 0.61, 0.01, 0.54, 0.54, 0.  ],
       [0.  , 0.18, 0.94, 0.74, 0.04, 0.14, 0.  ],
       [0.  , 0.71, 0.01, 0.7 , 0.29, 0.66, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 # False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(np.arange(4)+1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
np.diag(np.arange(4)+1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
X = np.zeros((8,8))
X[1::2,::2] = 1
X[::2, 1::2] = 1
X

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

np.tile is a NumPy function that constructs a new array by repeating an input array in a tiled (repeated) manner.

In [23]:
np.tile(([0,1],[1,0]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
X = np.random.uniform(15, 45, (5,5))
(X - np.mean(X)) / np.std(X)

array([[ 1.18276106, -0.94755133,  0.72301132, -0.59192941, -1.00751659],
       [-1.42531834,  1.41282618, -0.8429196 , -0.0945275 , -1.28977824],
       [ 0.44229916, -0.24321209, -0.57726202,  1.59211135,  1.15517162],
       [-0.57189729,  0.28132004, -0.26801807, -0.57865308,  1.04164861],
       [-1.34107757,  1.58781789, -0.3962474 , -0.90334621,  1.66028753]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
np.ones(shape=(5,3)) @ np.ones(shape=(3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
Z = np.arange(11)
Z[(3 < Z) & (8 > Z)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) # overriden sum from numpy

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z = np.array([4, 2])

In [30]:
Z ** Z

array([256,   4])

In [31]:
2 << Z >> 2

array([8, 2])

In [32]:
Z <- Z

array([False, False])

In [33]:
1j * Z

array([0.+4.j, 0.+2.j])

In [34]:
Z/1/1

array([4., 2.])

In [35]:
# Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
#np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/t5/ct5bhs3j6k18hj1qyrkwmvj00000gp/T/ipykernel_92501/703293450.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/t5/ct5bhs3j6k18hj1qyrkwmvj00000gp/T/ipykernel_92501/703293450.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

In [37]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
print(Z.round(0))

[ 6.30094049  5.15626244 -7.10116992  3.72336333  7.34636128  8.32172124
 -7.82216497  3.43148989 -3.94533617  7.14682408]
[ 7.  6. -8.  4.  8.  9. -8.  4. -4.  8.]
[ 6.  5. -7.  4.  7.  8. -8.  3. -4.  7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [38]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [39]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
np.sqrt(-1) 

/var/folders/t5/ct5bhs3j6k18hj1qyrkwmvj00000gp/T/ipykernel_92501/3347172139.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


np.float64(nan)

In [41]:
np.emath.sqrt(-1)

np.complex128(1j)

In [42]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/t5/ct5bhs3j6k18hj1qyrkwmvj00000gp/T/ipykernel_92501/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [43]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [44]:
np.arange('2016-07-01', '2016-08-01', dtype=np.datetime64)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [45]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [46]:
Z = np.random.uniform(0,10,10)
Z

array([0.87195573, 7.93550661, 6.23777779, 9.59468463, 2.63047787,
       1.49070647, 4.14924142, 8.06332069, 1.95780145, 7.41257224])

In [47]:
Z // 1

array([0., 7., 6., 9., 2., 1., 4., 8., 1., 7.])

In [48]:
Z - Z % 1

array([0., 7., 6., 9., 2., 1., 4., 8., 1., 7.])

In [49]:
Z.astype(int)

array([0, 7, 6, 9, 2, 1, 4, 8, 1, 7])

In [50]:
np.trunc(Z)

array([0., 7., 6., 9., 2., 1., 4., 8., 1., 7.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [51]:
Z = np.zeros((5,5))
Z += np.arange(0,5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [52]:
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [53]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [54]:
X = np.random.random(10)
X.sort()
X

array([0.00964796, 0.03302779, 0.13422979, 0.15688752, 0.30653007,
       0.3144794 , 0.37219273, 0.6469902 , 0.9207574 , 0.93846931])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [55]:
np.add.reduce(X)

np.float64(3.8332121449106493)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [56]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.allclose(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [57]:
A.flags.writeable = False
try:
    A[0]=0
except Exception:
    print("You can't")

You can't


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [58]:
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
R, T

(array([0.54028325, 0.74856972, 0.99808711, 0.58213681, 1.14261369,
        1.30830023, 0.26708813, 0.77323502, 0.71271423, 0.89514773]),
 array([0.8759778 , 0.7055186 , 0.00155555, 1.16766965, 0.52244385,
        0.72286633, 0.57044687, 1.38726625, 1.14740109, 0.75668851]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [59]:
X = np.random.random(10)
X[X.argmax()] = 0
X

array([0.02613081, 0.74288726, 0.21052871, 0.        , 0.34294816,
       0.42708411, 0.07302967, 0.14924096, 0.57523053, 0.45941139])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [60]:
np.meshgrid(np.linspace(0,1,5),
            np.linspace(0,1,5))

(array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]]))

In [61]:
Z = np.zeros((5,5), dtype=[('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [62]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [64]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [65]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(v-Z)).argmin()
Z[index]

np.int64(68)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [66]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Z

array([(([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.]))],
      dtype=[('position', [('x', '<f8', (1,)), ('y', '<f8', (1,))]), ('color', [('r', '<f8', (1,)), ('g', '<f8', (1,)), ('b', '<f8', (1,))])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [67]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


[[0.         0.0843733  0.46220124 0.84361025 0.21045952 0.63200093
  1.20335357 0.86868723 0.65808856 0.86679618 0.35232798 1.10048311
  0.4749255  0.47621077 0.18716673 0.52200363 0.71111346 0.48706798
  0.62760756 0.47991694 0.16116812 0.68470803 0.9212444  0.12424654
  0.33116465 0.70196224 0.67736379 0.84571251 0.41158699 0.39384488
  0.05954288 0.50929561 0.31191755 0.85056394 0.15963343 0.02111138
  0.9707571  0.55387936 0.41238021 0.79449832 0.81469496 0.19756549
  0.20950382 0.92683253 1.029627   0.82266973 0.72304393 0.28268128
  0.33995992 0.79784191 0.30609666 0.06152396 0.65887455 0.53086165
  0.38742448 0.81241098 0.65828732 0.21266235 0.26400451 0.90757215
  0.80934793 0.42908071 0.64522842 0.12574728 0.915172   0.50833757
  0.59729633 0.23097452 0.79434033 0.23665106 0.22810026 0.39937948
  0.77234808 0.83563732 0.8882933  0.79401123 0.10215843 0.31033688
  0.54912019 0.46736807 0.4242239  0.76210644 0.37700207 0.76119508
  0.32300609 0.39264788 0.8629661  0.62840876 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [68]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[25 43 92 41  1 24 41 58 35 43]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [69]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int64)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [70]:
for idx, value in np.ndenumerate(Z):
    print(idx, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) -1
(1, 2) -1
(1, 3) 7
(1, 4) 8
(2, 0) -1
(2, 1) -1
(2, 2) 9
(2, 3) 10
(2, 4) 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [71]:
X, Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
G

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [72]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [73]:
X = np.random.rand(5,10)

Y = X - X.mean(axis=1, keepdims=True)

Y

array([[-0.0050201 ,  0.27392832, -0.01955757,  0.3003949 , -0.26540535,
         0.14014319,  0.34557709, -0.42715638, -0.51839103,  0.17548693],
       [-0.32915073, -0.05666525, -0.32758026,  0.05461984, -0.33319845,
         0.30284019,  0.39520787,  0.39322056,  0.15550898, -0.25480275],
       [-0.30970952, -0.00498703,  0.32420591, -0.26061758, -0.10056729,
         0.30215316,  0.4509418 , -0.19731039,  0.089942  , -0.29405105],
       [ 0.33443738, -0.37451113, -0.16972192, -0.09174771,  0.2293593 ,
        -0.13102259,  0.15947101, -0.19517868,  0.40041491, -0.16150056],
       [ 0.10751366,  0.02114692,  0.3590459 ,  0.22182456,  0.1121186 ,
        -0.11275578,  0.02633151, -0.13861397, -0.44676023, -0.14985118]])

#### 59. How to sort an array by the nth column? (★★☆)

In [74]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 6 5]
 [3 8 2]
 [0 9 8]]
[[5 6 5]
 [3 8 2]
 [0 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [75]:
Z = np.random.randint(0,2,(3,10))
Z

array([[0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 1, 1]])

In [76]:
(~Z.any(axis=0)).any()

np.True_

#### 61. Find the nearest value from a given value in an array (★★☆)

In [77]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.28619675 0.58094833 0.69981903 0.92358341 0.13945394 0.70100993
 0.48419832 0.07234385 0.38624289 0.97796977]
0.4841983161652149


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [78]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [79]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(5), "numbers_array")
print(Z.name)

numbers_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z, I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [9 6 1 6 3 2 3 5 2 5 1 4 5 2 5 5 8 3 3 8]
[1. 3. 4. 5. 2. 6. 3. 1. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
binc = np.bincount(I,X)
print(binc)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [82]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[57 53 45 54]
 [60 48 38 50]
 [58 55 45 40]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [84]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.41856132 0.69986621 0.58668666 0.52004981 0.40125638 0.40870967
 0.57345355 0.5353166  0.5026799  0.38583231]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.einsum("ij,ji->i", A, B)

array([1.92495063, 0.81921328, 0.95984074, 1.4909807 , 1.35167801])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [86]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [87]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [88]:
print(A * B[:,:,np.newaxis])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [89]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
A

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [90]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 6, 25) ( 6, 42) ( 9, 45) ( 9, 86) (10, 22) (10, 34) (12, 59) (12, 76)
 (13, 26) (13, 39) (13, 64) (13, 88) (16, 27) (16, 93) (22, 34) (25, 42)
 (26, 39) (27, 67) (27, 72) (27, 93) (39, 73) (39, 97) (45, 86) (59, 76)
 (62, 79) (62, 84) (64, 88) (67, 72) (73, 97) (79, 84)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [91]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def calculate_moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(calculate_moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [94]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [95]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.48516422, -0.40114315,  0.5794954 ,  0.68316974, -0.73859619,
       -0.50342762, -0.25772257, -0.05533324,  0.81699481,  0.16324045,
        0.71456363, -0.79744594,  0.05561829, -0.86732089, -0.26825473,
        0.99649712,  0.26715607, -0.8057013 ,  0.60436876, -0.13064611,
       -0.06334228, -0.12134816,  0.92325305,  0.09773945,  0.22740565,
       -0.91125867,  0.08527621,  0.99987569, -0.19149209,  0.30538139,
        0.73055522,  0.99751562, -0.82487024, -0.61334569,  0.79047039,
        0.74917436, -0.62600647,  0.50337322, -0.0232879 ,  0.20806666,
       -0.50525175,  0.18784547, -0.67516364, -0.70655753, -0.10308294,
        0.85763918,  0.27360053, -0.7363082 ,  0.16248685,  0.97466197,
       -0.24487696,  0.70577912, -0.44103929, -0.58782528,  0.3695947 ,
       -0.81260896, -0.55976063, -0.2242052 , -0.56551863, -0.45041334,
        0.63375461, -0.02426159, -0.79022269, -0.70151528, -0.76121449,
       -0.30979154,  0.4409987 , -0.03989252,  0.35236994,  0.62

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

def calulate_distance(P0,P1,p):
    v = P1- P0 
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1 
    norm = np.linalg.norm(v,axis=1)   
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm 

    return d

print(calulate_distance(P0, P1, p))

[12.19045497  8.55229332  3.27159963 10.07909902  3.40905527 10.34138245
  1.19580288  8.04552212  7.83117487 11.67607695]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([calulate_distance(P0,P1,p_i) for p_i in p]))

[[4.31127182e+00 9.54778402e+00 2.19370245e+00 7.84014159e+00
  1.27066249e+01 3.46477444e+00 8.82040880e-01 4.05965484e+00
  4.13286135e+00 2.15277556e+00]
 [1.17662082e+01 1.36917965e+01 1.43528575e+01 1.76236262e+01
  1.69692902e+01 5.97936157e-01 1.31778578e+01 8.27307944e+00
  2.24934360e+00 1.23136038e+01]
 [4.02286256e+00 1.07766552e+01 2.64977074e+00 6.26143640e+00
  1.38856909e+01 7.16479529e+00 3.87770121e+00 7.73097668e+00
  8.71626084e+00 3.35693007e-01]
 [2.55629175e+00 5.78803318e+00 8.09575824e+00 7.94244475e+00
  9.00956095e+00 3.05359739e+00 6.57351561e+00 5.61133758e-01
  3.05584199e+00 2.61474322e+00]
 [6.47878072e+00 1.26747682e+01 3.21741418e-01 9.02402797e+00
  1.58055467e+01 7.59723428e+00 1.47050098e+00 4.89352042e+00
  8.27732867e+00 3.13674739e+00]
 [7.13052030e+00 2.66977294e+00 1.97042136e+00 2.11494929e+00
  4.97603313e-01 7.26826496e+00 7.36778828e-02 9.51989005e+00
  4.35604809e+00 7.43792331e+00]
 [7.18332407e+00 3.54405531e+00 4.54407605e+00 1.45425678e

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (9,9)

R = np.ones(shape, dtype=Z.dtype)*fill
print(R)
P  = np.array(list(position)).astype(int)
print(P)
Rs = np.array(list(R.shape)).astype(int)
print(Rs)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[tuple(r)] = Z[tuple(z)]
print(Z)
print(R)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[9 9]
[5 5]
[[5 8 0 5 9 4 0 9 9 0]
 [6 6 8 4 3 8 7 7 2 2]
 [2 3 1 0 4 0 2 0 4 3]
 [7 9 4 7 9 3 8 4 1 8]
 [5 6 2 7 6 1 0 7 5 4]
 [4 3 8 9 5 0 8 8 2 8]
 [6 3 4 0 9 7 5 2 2 1]
 [4 8 5 7 8 4 3 3 0 7]
 [7 2 5 0 6 8 4 3 7 0]
 [1 6 6 3 3 9 7 7 5 9]]
[[3 0 7 0 0]
 [3 7 0 0 0]
 [7 5 9 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [99]:
from numpy.lib import stride_tricks

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4)) # 4 is a size of uint32 in bytes
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Using SVD
U, s, Vt = np.linalg.svd(A)

rank = np.sum(s > 1e-10) 

print(f"Singular values: {s}")
print(f"Rank: {rank}")

Singular values: [1.68481034e+01 1.06836951e+00 3.35890790e-16]
Rank: 2


In [101]:
rank = np.linalg.matrix_rank(A)
print(rank)

2


#### 83. How to find the most frequent value in an array?

In [102]:
A = np.random.randint(0, 10, 30)
print(A)
print(np.bincount(A).argmax())

[7 5 9 4 4 0 7 8 8 3 7 9 6 8 0 0 7 8 6 5 7 5 8 1 3 9 5 3 9 8]
8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [103]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 3 1]
   [2 3 0]
   [0 2 4]]

  [[3 1 3]
   [3 0 0]
   [2 4 4]]

  [[1 3 4]
   [0 0 0]
   [4 4 0]]

  [[3 4 3]
   [0 0 1]
   [4 0 1]]

  [[4 3 3]
   [0 1 2]
   [0 1 2]]

  [[3 3 3]
   [1 2 2]
   [1 2 0]]

  [[3 3 3]
   [2 2 1]
   [2 0 3]]

  [[3 3 2]
   [2 1 0]
   [0 3 0]]]


 [[[2 3 0]
   [0 2 4]
   [1 0 1]]

  [[3 0 0]
   [2 4 4]
   [0 1 1]]

  [[0 0 0]
   [4 4 0]
   [1 1 2]]

  [[0 0 1]
   [4 0 1]
   [1 2 0]]

  [[0 1 2]
   [0 1 2]
   [2 0 0]]

  [[1 2 2]
   [1 2 0]
   [0 0 4]]

  [[2 2 1]
   [2 0 3]
   [0 4 2]]

  [[2 1 0]
   [0 3 0]
   [4 2 3]]]


 [[[0 2 4]
   [1 0 1]
   [4 3 1]]

  [[2 4 4]
   [0 1 1]
   [3 1 2]]

  [[4 4 0]
   [1 1 2]
   [1 2 1]]

  [[4 0 1]
   [1 2 0]
   [2 1 1]]

  [[0 1 2]
   [2 0 0]
   [1 1 0]]

  [[1 2 0]
   [0 0 4]
   [1 0 1]]

  [[2 0 3]
   [0 4 2]
   [0 1 0]]

  [[0 3 0]
   [4 2 3]
   [1 0 1]]]


 [[[1 0 1]
   [4 3 1]
   [2 3 0]]

  [[0 1 1]
   [3 1 2]
   [3 0 0]]

  [[1 1 2]
   [1 2 1]
   [0 0 1]]

  [[1 2 0]
   [2 1 1]
   [0 1 2]]

  [[2 0 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [104]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  2  8  8  5]
 [ 2  3  8  5  1]
 [ 8  8  8 42  3]
 [ 8  5 42  6  7]
 [ 5  1  3  7  0]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [105]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [106]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print(Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [ ]:
def cartesian_product(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    print(ix)

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian_product(([1, 2, 3], [4, 5], [6, 7])))

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]]
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [110]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


/var/folders/t5/ct5bhs3j6k18hj1qyrkwmvj00000gp/T/ipykernel_92501/100570611.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [111]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

421 ms ± 3.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
71.2 ms ± 4.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
79.5 ms ± 1.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [112]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
print(C)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[[[False False]
   [False False]]

  [[False  True]
   [False  True]]

  [[ True False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [ True False]]]


 [[[False  True]
   [False  True]]

  [[False False]
   [ True False]]

  [[False  True]
   [False  True]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[ True False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False  True]
   [False  True]]

  [[False  True]
   [False  True]]]


 [[[False False]
   [False False]]

  [[ True False]
   [False False]]

  [[ True False]
   [False False]]]


 [[[False False]
   [ True False]]

  [[False False]
   [ True False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [False False]]

  [[False False]
   [False False]]

  [[False  True]
   [False  True]]]]
[0 2 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [113]:
Z = np.random.randint(0,5,(10,3))
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 1]
 [1 3 4]
 [3 4 2]
 [1 2 3]
 [1 3 1]
 [2 4 4]
 [0 3 4]
 [3 0 3]
 [4 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [114]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [115]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)
print(uZ.shape)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
(5, 3)


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [116]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[5.82933185e-01, 3.60394267e-01, 4.21205278e-01, 7.80258616e-01,
        7.28221588e-01, 4.48395333e-01, 3.29045929e-01, 3.00576260e-01,
        5.36489036e-01, 6.75303110e-01],
       [6.53427873e-01, 4.03977103e-01, 4.72142050e-01, 8.74616064e-01,
        8.16286147e-01, 5.02620226e-01, 3.68837779e-01, 3.36925245e-01,
        6.01367187e-01, 7.56968185e-01],
       [1.19440610e-03, 7.38433021e-04, 8.63032281e-04, 1.59871779e-03,
        1.49209606e-03, 9.18743584e-04, 6.74201566e-04, 6.15868386e-04,
        1.09924395e-03, 1.38366828e-03],
       [2.36791478e-01, 1.46394635e-01, 1.71096487e-01, 3.16946428e-01,
        2.95808629e-01, 1.82141275e-01, 1.33660724e-01, 1.22096149e-01,
        2.17925544e-01, 2.74312778e-01],
       [3.76036159e-01, 2.32481663e-01, 2.71709381e-01, 5.03326043e-01,
        4.69758209e-01, 2.89249031e-01, 2.12259605e-01, 1.93894506e-01,
        3.46076157e-01, 4.35621774e-01],
       [4.67244570e-01, 2.88870610e-01, 3.37613099e-01, 6.25408900e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [118]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size)) # indices to samples
means = X[idx].mean(axis=1) # mean of each sample
confint = np.percentile(means, [2.5, 97.5]) # confidence interval
print(confint)

[-0.36093826  0.05354905]
